In [1]:
import numpy as np

In [1]:
z = [1, 2, 3, 4, 5, 6]

In [2]:
z 

[1, 2, 3, 4, 5, 6]

In [4]:
w = 2 * z
w
# el resultado no es de la multiplicación porque z no es un array (arreglo)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [5]:
x = [6, 5, 4, 3, 2, 1]

In [6]:
r = w + x 
r 
# en este mismo ejemplo vemos que se concatenaron, no se hizo la suma aritmética

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1]

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([6, 5, 4, 3, 2, 1])

In [14]:
a

array([1, 2, 3, 4, 5, 6])

In [15]:
c = 2*a
c

array([ 2,  4,  6,  8, 10, 12])

# TAREA

De la diapositiva 10 a la última

In [12]:
a = [1, 3, 5, 7, 9]
print(a[2:4])

b2 = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
print(b2[0])

# Operadores aritméticos
# Suma
b = [1, 3, 5, 7, 9]
c = a + b
print(c)

[5, 7]
[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]


In [13]:
# Funciones de numpy

# Valor absoluto
ar = np.array([-1, -2, 3, -4])
print(np.abs(ar)) 

[1 2 3 4]


In [14]:
# Suma de arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.add(arr1, arr2))  

[5 7 9]


In [15]:
# Valores binomiales
print(np.random.binomial(n=10, p=0.5, size=5)) 

[5 7 4 2 3]


In [16]:
# Producto acumulativo 

arr = np.array([1, 2, 3, 4])
print(np.cumprod(arr)) 

[ 1  2  6 24]


In [ ]:
# Suma acumulativa

arr = np.array([1, 2, 3, 4])
print(np.cumsum(arr)) 

In [17]:
# Histograma

data = np.array([1, 2, 1, 2, 3, 3, 3, 4, 5])
hist, bins = np.histogram(data, bins=5)
print(hist)  
print(bins)

[2 2 3 1 1]
[1.  1.8 2.6 3.4 4.2 5. ]


In [18]:
# Multiplicación de arrays

print(np.multiply(a, b))

[ 1  9 25 49 81]


In [23]:
# Generar número entero aleatorio

print(np.random.randint(1, 10, size=2))

[1 3]


In [26]:
# Reorganizar aleatoriamente un array

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)  

[4 2 5 1 3]


In [27]:
# Transponer una matriz

print(np.transpose(b2))

[[ 2  1]
 [ 4  3]
 [ 6  5]
 [ 8  7]
 [10  9]]


## Vectores

In [31]:
x = np.array([1, 3, 5, 7, 9])
y = np.array([3, 5, 6, 7, 9])
z = x + y
print(z)
type(z)


[ 4  8 11 14 18]


numpy.ndarray

In [33]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]
a = np.array(l)
print(a)
a.shape

[[1 2 3]
 [3 6 9]
 [2 4 6]]


(3, 3)

## Arreglos

In [37]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [38]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [39]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


## Creación y uso de arreglos

In [43]:
d = np.arange(5)
print(d)
print(d*4)

np.random.rand(5,5)

[0 1 2 3 4]
[ 0  4  8 12 16]


array([[0.16409756, 0.18392307, 0.75378528, 0.30544184, 0.9404767 ],
       [0.52078282, 0.9587367 , 0.72596438, 0.85005343, 0.40380983],
       [0.64887101, 0.06880717, 0.30855822, 0.7680164 , 0.29741869],
       [0.02631867, 0.73938366, 0.82829731, 0.0326027 , 0.20004254],
       [0.48860167, 0.84525903, 0.91874055, 0.76439424, 0.07964343]])

In [56]:
a = np.arange(4,0)
b = a * 23.4
r = b/(a+1)
r += 10
arr = np.arange(100, 200)
select = [5, 25, 50, 75, -5]
print(arr[select])

[105 125 150 175 195]


## Sort

In [60]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
arr.sort() 
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [61]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

## Funciones

In [64]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

array([6., 4., 9.])

In [65]:
a - b

array([-4.,  0., -3.])

In [66]:
b / a

array([5., 1., 2.])